accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout')
]

comparer/urls.py
from django.urls import path
from . import views

app_name = "comparer"

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('video-search/', views.video_search, name="video-search"),
    path('video-id/', views.video_id, name="video-id")
]

vilytic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include('accounts.urls'), name="accounts"),
    path('comparer/', include('comparer.urls'), name="comparer"),
    path('contact/', views.contact, name="contact"),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

comparer/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': "Username"})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': "Email"})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': "Password"})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': "Confirm Password"})

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserCreateForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .decorators import unauthenticated_user
from django.contrib import messages

# Create your views here.


@unauthenticated_user
def register(request):
    form = UserCreateForm()

    if request.method == "POST":
        form = UserCreateForm(request.POST)

        if form.is_valid():
            user = form.save()
            messages.success(request, 'Account was created')

            return redirect('accounts:login')
    return render(request, 'accounts/register.html', {'form': form})


@unauthenticated_user
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('comparer:dashboard')
        else:
            messages.info(request, "Username or password is incorrect")

    return render(request, 'accounts/login.html', {})


@login_required
def logout_user(request):
    logout(request)
    return redirect('index')

comparer/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.conf import settings
from rest_framework.decorators import api_view
from rest_framework.response import Response
from slugify import slugify
import requests
from rest_framework import status
from rest_framework.decorators import throttle_classes
from .throttles import VideoIdTrottle, VideoSearchTrottle


# Create your views here.


def dashboard(request):
    return render(request, 'comparer/dashboard.html')

# API


@api_view(["GET"])
@throttle_classes([VideoSearchTrottle])
def video_search(request):
    search_url = 'https://www.googleapis.com/youtube/v3/search'
    raw_query = request.GET.get('query').split('-')
    query = " ".join(raw_query)
    params = {
        'part': 'snippet',
        'q': query,
        'key': settings.YOUTUBE_API_KEY,
        'maxResults': 5
    }

    r = requests.get(search_url, params=params)

    data = {
        "items": []
    }

    for video in r.json()['items']:
        if 'videoId' in video['id']:
            video_data = {
                "id": video['id']['videoId'],
                "title": video['snippet']['title'],
                "thumbnail": video['snippet']['thumbnails']['high']['url'],
            }

            data["items"].append(video_data)

    return Response(data)


@api_view(['GET'])
@throttle_classes([VideoIdTrottle])
def video_id(request):
    video_id = request.GET.get('id')
    url = 'https://www.googleapis.com/youtube/v3/videos'
    params = {
        "part": 'statistics,snippet',
        'key': settings.YOUTUBE_API_KEY,
        "id": video_id
    }

    r = requests.get(url, params=params)
    data = r.json()

    if len(data['items']) > 0:
        item = data['items'][0]

        video_data = {
            "stats": {
                "views": item['statistics']['viewCount'],
                "likes": item['statistics']['likeCount'],
                "favorites": item['statistics']['favoriteCount'],
                "comments": item['statistics']['commentCount'],
            },
            "id": item['id'],
            "title": item['snippet']['title'],
            "thumbnail": item['snippet']['thumbnails']['high']['url'],
        }

        return Response(video_data)
    else:
        return Response("Video not found.", status=status.HTTP_404_NOT_FOUND)

vilytic/views.py
from django.shortcuts import render
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings


def index(request):
    print(request)
    return render(request, 'index.html')


def contact(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']

        template = render_to_string('email_template.html', {
            'name': request.POST['name'],
            'email': request.POST['email'],
            'message': request.POST['message']
        })

        email = EmailMessage(
            "Vilytic",
            template,
            settings.EMAIL_HOST_USER,
            ['diegoabdov@gmail.com']
        )
        email.fail_silently = False
        email.send()
        return render(request, 'contact_confirm.html', {"name": name})
    else:
        return render(request, 'index.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block links %}

<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<title>Vilytic | Login</title>

{% endblock %}

{% block content %}



<div style="background-color: #6240C8;" class="dash-nav">
    {% include 'navbar.html' %}
</div>




<main class="page-auth login-container">
  <div>
      <div class="row">
          <div class="col-lg-10 offset-lg-1">
              <section class="auth-wrapper">
                  <div class="row">
                      <div class="col-md-6 mb-4 mb-md-0 gray-bg p-5 shadow">
                        {% for message in messages %}
                            <div class="alert alert-info alert-dismissible fade show" role="alert">
                                {{message}}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                          <h2 class="auth-section-title">Log In</h2>
                          <p class="auth-section-subtitle">Sign in to your account to continue.</p>
                          <form method="POST">
                              {% csrf_token %}
                              <div class="form-group mt-4">
                                  <label for="username">Username <sup>*</sup></label>
                                  <input type="text" class="form-control" id="username" placeholder="Username *" name="username">
                              </div>
                              <div class="form-group mt-4">
                                  <label for="password">Password <sup>*</sup></label>
                                  <input type="password" class="form-control" id="password" placeholder="Password *" name="password">
                              </div>
                              <button class="theme-btn mt-4 w-100" type="submit">Submit</button>
                          </form>

                          <p class="mb-0 mt-4">
                              <p class="text-dark">New User? <a href="{% url 'accounts:register' %}">Sign Up</a></p>
                          </p>
                      </div>
                      <div class="col-md-6 d-flex align-items-center">
                          <img src="{% static 'images/login.svg' %}" alt="login" class="img-fluid">
                      </div>
                  </div>
              </section>
          </div>
      </div>
  </div>
</main>

<footer class="sticky-footer bg-white pt-4 mb-4">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Vilytic 2021</span>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle-5.0.0.alpha-1-min.js' %}"></script>



{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block links %}

<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/register.css' %}">

<title>Vilytic | Register</title>

{% endblock %}

{% block content %}
<div style="background-color: #6240C8;" class="dash-nav">
    {% include 'navbar.html' %}
</div>

<main class="page-auth register-container">
  <div>
      <div class="row">
          <div class="col-lg-10 offset-lg-1">
              <section class="auth-wrapper">
                  <div class="row">
                      <div class="col-md-6 mb-4 mb-md-0 gray-bg p-5 shadow">
                          <h2 class="auth-section-title">Create account</h2>
                          <p class="auth-section-subtitle">Create your account to continue.</p>
                          <form method="POST">
                              {% csrf_token %}
                              <div class="form-group mt-4">
                                <label for="username">Username <sup>*</sup></label>
                                {{form.username}}
                            </div>
                              <div class="form-group mt-4">
                                  <label for="email">Email <sup>*</sup></label>
                                  {{form.email}}
                              </div>
                              <div class="form-group mt-4">
                                  <label for="password">Password <sup>*</sup></label>
                                  {{form.password1}}
                              </div>
                              <div class="form-group mt-4">
                                  <label for="confirmPassword">Confirm Password <sup>*</sup></label>
                                  {{form.password2}}
                              </div>
                              <button class="theme-btn mt-4 w-100" type="submit">Create account</button>
                          </form>
                          <p class="mb-0 mt-4">
                              <p class="text-dark">Already have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
                          </p>
                      </div>
                      <div class="col-md-6 d-flex align-items-center">
                          <img src="{% static 'images/register.svg' %}" alt="register" class="img-fluid">
                      </div>
                  </div>
              </section>
          </div>
      </div>
  </div>
</main>

<footer class="sticky-footer bg-white pt-4 mb-4">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Vilytic 2021</span>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle-5.0.0.alpha-1-min.js' %}"></script>

{% endblock %}

comparer/templates/comparer/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block links %}


<link href="{% static 'css/main.css' %}" rel="stylesheet">
<link href="{% static 'css/custom.css' %}" rel="stylesheet">
<link href="{% static 'css/ReactToastify.css' %}" rel="stylesheet">

<title>Vilytic | Comparer</title>

{% endblock %}

{% block content %}

<!-- Page Wrapper -->
<div id="wrapper gray-bg">

    <!-- Sidebar -->

    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content" style="background-color: whitesmoke">
            <div style="background-color: #6240C8;" class="dash-nav">
                {% include 'navbar.html' %}
            </div>



            <!-- Begin Page Content -->
            <div class="container">


                <div id="root"></div>







            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white pt-4">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Vilytic 2021</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>




<!-- React -->
<script src="{% static 'js/bootstrap.bundle-5.0.0.alpha-1-min.js' %}"></script>

<script src="{% static 'index-bundle.js' %}"></script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/1b2de11c6b.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'favicon.ico' %}">
    {% block links %}{% endblock %}
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/contact_confirm.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-center mt-5">
    <h1>¡Thank you for contacting {{name}}!</h1>
    <p>Your message was sent successfully. I will try to get back to you as soon as possible.</p>
    <a href="{% url 'index' %}"><button class="btn btn-primary mt-2">Home</button></a>
</div>

{% endblock %}

templates/email_template.html
{{message}}

{{name}}

{{email}}

templates/navbar.html
{% load static %}
<!-- ========================= header start ========================= -->
<header class="header">
  <div class="navbar-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <nav class="navbar navbar-expand-lg justify-content-between">
            <a class="navbar-brand" href="{% url 'index' %}">
              <img src="{% static 'images/logo.png' %}" alt="Logo" />
            </a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
            </button>

            <div
              class="collapse navbar-collapse sub-menu-bar"
              id="navbarSupportedContent"
            >
              <ul id="nav" class="navbar-nav">
                <li class="nav-item">
                  <a class="page-scroll" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="page-scroll" href="{% url 'comparer:dashboard' %}"
                    >Compare</a
                  >
                </li>
              </ul>
            </div>
            <!-- navbar collapse -->
          </nav>
          <!-- navbar -->
        </div>
      </div>
      <!-- row -->
    </div>
    <!-- container -->
  </div>
  <!-- navbar area -->
</header>
<!-- ========================= header end ========================= -->